MINOR: Cli script fix undefined variable file
I am not sure if this is appropriate fix for this due to my limited knowledge of python. I suspect there use to be a file variable defined. The above is a quick fix for following error

NameError: name 'file' is not defined